global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:80"]

  - job_name: "node-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["node-exporter:9100"]
